- name: Install required packages
  become: true
  apt:
   name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
   update_cache: yes
   state: latest

- name: Import GPG Key for Docker repository
  become: true
  apt_key:
   url: https://download.docker.com/linux/ubuntu/gpg
   state: present

- name: Add aptitude Docker repository
  apt_repository:
   repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
   state: present

- name: Install Docker engine
  become: true
  apt:
   name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
   update_cache: yes
   state: latest
