#!/bin/bash
# 20210313 - Script created by David López
version=1.0

# Getting local IP address
mylocalip="$(hostname -I)"

# Getting public IP address
mypublicip="$(curl --silent http://ifconfig.io)"

# Gettiong default gateway IP address (router address)
mydefaultgw="$(ip r | grep default | awk '{print $3}')"

# Getting hostname
myhostname="$(hostname)"

# Getting domain name (if is assigned)
mydomain="$(hostname -d)"

# Check network connectivity to default gateway
if ping -q -c 1 -W 1 $mydefaultgw > /dev/null;
then
	status="UP"
	echo "Connection to $mydefaultgw is $status"
	exit 0
else
	status="DOWN"
	echo "Connection to $mydefaultgw is $status"
	exit 1
fi

# JSON Encode result -> to use this is necessary to comment exit in if statement
# js_out="{\"localip\":${mylocalip},\"publicip\":${mypublicip},\"hostname\":${myhostname},\"domain\":${mydomain},\"status\":${status}}"
