#!/bin/bash
# 20210313 - Script created by David López
version=1.0

# Getting local IP address
mylocalip="$(hostname -I)"

# Getting public IP address
mypublicip="$(curl --silent http://ifconfig.io)"

# Gettiong default gateway IP address (router address)
mydefaultgw="$(ip r | grep default | awk '{print $3}')"

# Getting hostname
myhostname="$(hostname)"

# Getting domain name (if is assigned)
mydomain="$(hostname -d)"

# Check network connectivity to default gateway
if ping -q -c 1 -W 1 $mydefaultgw > /dev/null;
then
	echo "Connection to $mydefaultgw is up"
	exit 0
else
	echo "Connection to $mydefaultgw is down"
	exit 1
fi

# Show result in terminal
# echo "Local IP: $mylocalip and Public IP: $mypublicip using gateway: $mydefaultgw"
# echo "I'm in computer $myhostname in domain $mydomain"
